# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: {{ cookiecutter.project_license_spdx_identifier }}

version = 1

[[annotations]]
path = [
    "**/AGENTS.md",
    "*.README.md",
    "**/README.md"
]
SPDX-FileCopyrightText = '{{ cookiecutter.project_copyright_year}} {{ cookiecutter.project_copyright_holder_identity }}'
SPDX-License-Identifier = '{{ cookiecutter.project_license_spdx_identifier }}'
